### ISSUE TITLE
GEONATURE-DB - Todo list

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature-packaging#3]
- [x] Faire fonctionner avec un user non superuser

- [x] Supprimer les sudo
- [x] Créer une table de versionning dans la base
- [x] Gérer la base de donnée existante
- [x] Gérer les sorties d’erreur proprement
- [x] Capturer les erreurs SQL et arrêter l’installation
- [x] Supprimer la base en cours d'installation en cas d'erreur ou d'interruption (ne pas le faire sur un update)
- [ ] Tester les update
